---
- hosts: appserver
  vars:
    - http_port: 8080
    - tomcat_version: 9.0.50
  become: true

  tasks:
    - name: Install OpenJDK
      apt: name=openjdk-8-jdk state=latest

    - name: add group "tomcat"
      group: name=tomcat

    - name: add user "tomcat"
      user: name=tomcat group=tomcat createhome=yes

    - name: Download Tomcat archive
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/opt/"
        mode: 0755
      become: true

    - name: Extract Tomcat archive
      command: tar zxvf /opt/apache-tomcat-{{ tomcat_version }}.tar.gz -C /opt/ creates=/opt/apache-tomcat-{{ tomcat_version }}

    - name: Change ownership of Tomcat installation
      file: path=/opt/apache-tomcat-{{ tomcat_version }} owner=tomcat group=tomcat state=directory recurse=yes
      register: result

    - name: Change the working directory to Tomcat Apache before running Tomcat Apache
      shell: ./bin/startup.sh
      args:
       chdir: /opt/apache-tomcat-{{ tomcat_version }}
      become: true 
      become_user: tomcat

    - name: Copy Tomcat systemd service file
      copy:
        content: |
          [Unit]
          Description=Apache Tomcat 9.0.50 Web Application Container
          After=network.target

          [Service]
          Type=forking
          Environment=JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          Environment=CATALINA_PID=/opt/apache-tomcat-9.0.50/temp/tomcat.pid
          Environment=CATALINA_HOME=/opt/apache-tomcat-9.0.50
          Environment=CATALINA_BASE=/opt/apache-tomcat-9.0.50
          Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
          Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'
          ExecStart=/opt/apache-tomcat-9.0.50/bin/startup.sh
          ExecStop=/opt/apache-tomcat-9.0.50/bin/shutdown.sh
          User=tomcat
          Group=tomcat
          UMask=0007
          RestartSec=10
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/tomcat.service
      notify:
        - Reload SystemD

    - name: Start Tomcat service
      systemd:
        name: tomcat
        state: started

    - name: Copy WAR file to web container
      copy:
        src: /mytmp/config_mng_proj1/target/hello-world-war-1.0.0.war
        dest: "/opt/apache-tomcat-{{ tomcat_version }}/webapps/"

    - name: Restart Tomcat service
      service:
        name: tomcat
        state: restarted

  handlers:
    - name: Reload SystemD
      systemd:
        name: tomcat
        state: reloaded

